import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/layout/Header";
import Footer from "../components/layout/Footer";
import { Toaster } from "react-hot-toast";

const inter = Inter({
  variable: '--font-sans',
  subsets: ['latin'],
  weight: ['300','400','600','700']
})

const robotoMono = Roboto_Mono({
  variable: '--font-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${robotoMono.variable}`}>
        <Header />
        <main style={{padding: '1rem', minHeight: '70vh'}}>{children}</main>
        <Toaster /> 
        <Footer />
      </body>
    </html>
  );
}
